Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
============== RESTART: C:\Users\prade\assign\Part3\devops_log.py ==============
total number of lines in the log file is= 11
Total Error in logs :  2
# WARNING: Error ID [123]
2019-4-1 13:33:45 [123] User1 logs in

2019-4-1 13:33:45 [123] User1 goes to search page

2019-4-1 13:33:46 [123] User1 types in search text

2019-4-1 13:33:50 [123] User1 clicks search button

2019-4-1 13:33:54 [123] ERROR: Some exception occured

# WARNING: Error ID [190]
2019-4-1 13:32:40 [190] User3 logs in

2019-4-1 13:33:49 [190] User3 runs some job

2019-4-1 13:33:57 [190] ERROR: Invalid input
>>> 
